[Feat] Prompt 교체가능하도록 구현 #17
kookmin-sw/capstone-2024-13 pull request #20
Opened 2024-03-13 06:43 UTC by hyunjoon0208

## 📌 개요 
 - close #17 
 - json파일에서 prompt, 질문리스트, AI 및 Human의 역할을 읽어오도록 구현
 - 주석추가
## 💻 작업사항 
## ✅ 변경로직 
 -

2024-03-13 06:45 UTC, younganswer requested changes
.env.sample이 다 지워졌는데, 복구해주세요

2024-03-13 14:19 UTC, woonsango commented on src/service/langserve/app/chain.py
> +retriever = vector_store.as_retriever()
어디에 쓰나요

2024-03-13 14:23 UTC, woonsango approved these changes

2024-03-14 01:26 UTC, hyunjoon0208 commented on src/service/langserve/app/chain.py
> +retriever = vector_store.as_retriever()
나중에 RAG에 적용하려고 합니다.

2024-03-14 01:36 UTC, younganswer approved these changes

2024-03-14 02:11 UTC, merged