[Feat] LLM API 구현 #5
kookmin-sw/capstone-2024-13 pull request #6
Opened 2024-03-11 08:43 UTC by hyunjoon0208

## 📌 개요 
 - close #5 
## 💻 작업사항 
 - llm api구현
## ✅ 변경로직 
 -
![Screenshot from 2024-03-11 17-00-11](https://github.com/kookmin-sw/capstone-2024-13/assets/54919634/66de89f7-e6b2-435a-b757-671ea5ef2e69)

2024-03-11 13:40 UTC, woonsango commented on src/service/llm/app/chain.py
> +)
test

2024-03-11 13:41 UTC, woonsango reviewed
좋은데요

2024-03-11 13:42 UTC, woonsango approved these changes

2024-03-11 13:43 UTC, woonsango requested changes
아쉬운데요

2024-03-11 13:56 UTC, jeongahn approved these changes

2024-03-12 02:25 UTC, woonsango approved these changes
아쉬운데요

2024-03-12 02:25 UTC, woonsango approved these changes
좋은데요

2024-03-12 02:25 UTC, woonsango approved these changes

2024-03-12 07:18 UTC, merged